name: Pull Request
on:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - 'master'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm ci

      - name: Test
        run: |
          npm run lint

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm ci

      - name: Test
        run: |
          npm test -- --coverage

      - name: Code Coverage Summary Report
        id: code_coverage
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'coverage/index.html'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm ci

      - name: Test
        run: |
          npm run build

  synth:
    name: Synthesize
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Set up Slug action
        uses: rlespinasse/github-slug-action@v3.x

      - name: Init STAGE variable
        run: echo "STAGE=pr-${{ github.event.number }}-${{ env.GITHUB_HEAD_REF_SLUG }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Synthesize
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'synth'
          cdk_args: '--require-approval never'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STAGE: ${{ env.STAGE }}

  diff:
    name: Diff
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Set up Slug action
        uses: rlespinasse/github-slug-action@v3.x

      - name: Init STAGE variable
        run: echo "STAGE=pr-${{ github.event.number }}-${{ env.GITHUB_HEAD_REF_SLUG }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          cdk_args: '--require-approval never'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STAGE: ${{ env.STAGE }}
